
server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcrud?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      properties:
        hibernate:
          format_sql: true
      database-platform: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
      hibernate:
        ddl-auto: create-drop
  application:
    name: SpringCRUD








